import { useMemo, useState } from 'react';
import { jsPDF } from 'jspdf';
import { BarChart, Bar, XAxis, YAxis, Tooltip, PieChart, Pie, Cell, ResponsiveContainer } from 'recharts';
import { format } from 'date-fns';
import { ptBR } from 'date-fns/locale';
import { storage } from './services/storage';
import { Order, Settings, Transaction, TransactionType } from './types/finance';
import { cashBalance, expensesByCategory, grossProfit, monthlyRevenue, pendingLoansBalance, totalOperationalExpenses } from './utils/finance';
const brl=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}); const now=()=>new Date().toISOString();
const tabs=['Dashboard','Transações','Encomendas','Gráficos','Configurações','Declaração','Backup'] as const;
export function App(){const [tab,setTab]=useState<(typeof tabs)[number]>('Dashboard');const [transactions,setTransactions]=useState<Transaction[]>(storage.getTransactions());const [orders,setOrders]=useState<Order[]>(storage.getOrders());const [settings,setSettings]=useState<Settings>(storage.getSettings());const [form,setForm]=useState<any>({type:'Receita',amount:0,date:format(new Date(),'yyyy-MM-dd'),category:'Vendas'});
const persistTx=(v:Transaction[])=>{setTransactions(v);storage.setTransactions(v)}; const persistOrders=(v:Order[])=>{setOrders(v);storage.setOrders(v)};
const month=new Date().getMonth(),year=new Date().getFullYear(); const monthRev=monthlyRevenue(transactions,month,year); const monthExp=transactions.filter(t=>t.type==='Despesa'&&t.date.startsWith(String(year))).reduce((a,b)=>a+b.amount,0);
const addTx=()=>{if(!form.amount||form.amount<=0||!form.date||!form.type||!form.category) return alert('Preencha campos obrigatórios'); if(form.type==='Empréstimo recebido'&&!form.person) return alert('Credor obrigatório'); const t:Transaction={id:crypto.randomUUID(),...form,createdAt:now(),updatedAt:now()}; persistTx([t,...transactions]); alert('Transação salva');};
const markDelivered=(o:Order)=>{const updated=orders.map(x=>x.id===o.id?{...x,status:'Entregue',updatedAt:now()}:x); persistOrders(updated); if(confirm('Criar receita automática?')){if(transactions.some(t=>t.linkedOrderId===o.id)) return alert('Receita já registrada'); persistTx([{id:crypto.randomUUID(),type:'Receita',category:'Encomendas',amount:o.value,date:o.deliveryDate,description:`Receita gerada pela encomenda de ${o.clientName}`,linkedOrderId:o.id,createdAt:now(),updatedAt:now()},...transactions])}};
const allocTotal=settings.allocation.capital+settings.allocation.salarios+settings.allocation.emergencia+settings.allocation.utilidades+settings.allocation.outros;
const report=()=>{const d=new jsPDF();d.text(`${settings.businessName} - Relatório ${settings.referenceYear}`,10,10);d.text(`Gerado em ${format(new Date(),'Pp',{locale:ptBR})}`,10,18);d.text(`Receita bruta: ${brl(transactions.filter(t=>t.type==='Receita').reduce((a,b)=>a+b.amount,0))}`,10,30);d.text(`Despesas: ${brl(totalOperationalExpenses(transactions))}`,10,38);d.text('Relatório auxiliar, não substitui orientação contábil.',10,50);d.save('relatorio-anual.pdf')};
const chartData=useMemo(()=>expensesByCategory(transactions),[transactions]);
return <div className='min-h-screen p-4 md:grid md:grid-cols-[220px_1fr] gap-4'><aside className='card h-fit'>{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className='block w-full text-left p-2 rounded hover:bg-gray-100'>{t}</button>)}</aside><main className='space-y-4'>
{tab==='Dashboard'&&<div className='grid md:grid-cols-5 gap-3'>{[['Saldo em Caixa',cashBalance(transactions),'text-green-600'],['Receitas do Mês',monthRev,'text-green-500'],['Despesas do Mês',monthExp,'text-red-500'],['Lucro Operacional',grossProfit(transactions),'text-blue-500'],['Empréstimos Pendentes',pendingLoansBalance(transactions),'text-amber-500']].map(([l,v,c])=><div className='card' key={String(l)}><p>{l}</p><b className={c as string}>{brl(v as number)}</b></div>)}</div>}
{tab==='Transações'&&<div className='card space-y-2'><p className='text-sm text-gray-500'>Os dados ficam salvos apenas neste navegador. Exporte um backup regularmente.</p><div className='grid md:grid-cols-6 gap-2'>{['type','amount','date','category','description','person'].map(k=><input key={k} placeholder={k} className='border rounded p-2' value={form[k]||''} onChange={e=>setForm({...form,[k]:k==='amount'?Number(e.target.value):e.target.value})}/>)}</div><button onClick={addTx} className='bg-green-600 text-white px-4 py-2 rounded'>Salvar transação</button><ul>{transactions.map(t=><li key={t.id} className='border-b py-2 flex justify-between'><span>{t.type} • {t.category} • {t.description}</span><span>{brl(t.amount)}</span></li>)}</ul></div>}
{tab==='Encomendas'&&<div className='card'><button onClick={()=>persistOrders([{id:crypto.randomUUID(),clientName:'Cliente',description:'Kit 100',deliveryDate:format(new Date(),'yyyy-MM-dd'),deliveryTime:'18:00',value:100,status:'Pendente',createdAt:now(),updatedAt:now()},...orders])} className='bg-violet-600 text-white px-4 py-2 rounded'>Nova encomenda</button><ul>{orders.map(o=><li key={o.id} className='py-2 flex justify-between'><span>{o.clientName} - {o.status}</span><button onClick={()=>markDelivered(o)} className='text-blue-600'>Marcar entregue</button></li>)}</ul></div>}
{tab==='Gráficos'&&<div className='grid md:grid-cols-2 gap-4'><div className='card h-64'><ResponsiveContainer><BarChart data={chartData}><XAxis dataKey='name'/><YAxis/><Tooltip/><Bar dataKey='value' fill='#ef4444'/></BarChart></ResponsiveContainer></div><div className='card h-64'><ResponsiveContainer><PieChart><Pie data={chartData} dataKey='value' nameKey='name'>{chartData.map((_,i)=><Cell key={i} fill={['#22c55e','#f59e0b','#3b82f6','#8b5cf6'][i%4]}/>)}</Pie></PieChart></ResponsiveContainer></div></div>}
{tab==='Configurações'&&<div className='card space-y-2'><input className='border p-2 rounded w-full' value={settings.businessName} onChange={e=>setSettings({...settings,businessName:e.target.value})}/><input className='border p-2 rounded w-full' value={settings.ownerName} onChange={e=>setSettings({...settings,ownerName:e.target.value})}/><p>Total alocação: {allocTotal}%</p><button disabled={allocTotal!==100} onClick={()=>{storage.setSettings(settings);alert('Configurações salvas')}} className='bg-blue-600 disabled:bg-gray-400 text-white px-4 py-2 rounded'>Salvar</button></div>}
{tab==='Declaração'&&<div className='card space-y-2'><p>Receita bruta (somente Receita): {brl(transactions.filter(t=>t.type==='Receita').reduce((a,b)=>a+b.amount,0))}</p><p>Não compõe receita: Aporte, Empréstimo recebido, Transferência</p><p>Despesas operacionais (somente Despesa): {brl(totalOperationalExpenses(transactions))}</p><p>Não compõe despesas operacionais: Retirada, Pagamento de empréstimo, Transferência</p><button onClick={report} className='bg-red-600 text-white px-4 py-2 rounded'>Gerar PDF</button></div>}
{tab==='Backup'&&<div className='card space-y-2'><button onClick={()=>{const data=storage.exportBackup();const b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='backup-financeiro.json';a.click();localStorage.setItem('cfl_last_backup',now())}} className='bg-emerald-600 text-white px-4 py-2 rounded'>Exportar JSON</button><input type='file' accept='application/json' onChange={async e=>{const f=e.target.files?.[0];if(!f)return;storage.importBackup(JSON.parse(await f.text()));location.reload()}}/><button onClick={()=>confirm('Limpar tudo?')&&(storage.clear(),location.reload())} className='bg-red-600 text-white px-4 py-2 rounded'>Limpar dados</button><p className='text-sm text-gray-500'>Último backup: {storage.getLastBackupAt()||'N/A'}</p></div>}
</main></div>}
